config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#top'
  get 'restaurants/top' => "restaurants#top"
  get 'restaurants/search' => "restaurants#search"
  get 'restaurants/data' => "restaurants#data"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
require 'json'
require 'net/https'
require "uri"

class RestaurantsController < ApplicationController
  def top
  end

  def search
    latitude = params[:latitude]
    longitude = params[:longitude]
    @range = params[:range]
    words = params[:word]
    data = {
      "keyid": "c64de82187c33b325c4ed6c51f3979ef",
      "latitude": latitude,
      "longitude": longitude,
      "range": @range,
      "freeword": words,
      "hit_per_page": 100
    }
    
    query = data.to_query
    uri = URI("https://api.gnavi.co.jp/RestSearchAPI/?"+query)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(uri)
    res = http.request(req)
    res_data = Hash.from_xml(res.body)
    if res_data.has_key?("response")
      datas = res_data["response"]["rest"]
      if datas.kind_of?(Array)
        @restaurants = Kaminari.paginate_array(datas).page(params[:page]).per(10)
      else
        @restaurant = datas
      end
    else
      flash[:danger] = res_data["gnavi"]["error"]["message"]
      redirect_to root_url
    end
  end

  def data
    id = params[:id]
    data = {
      "keyid": "c64de82187c33b325c4ed6c51f3979ef",
      "id": id
    }
    query = data.to_query
    uri = URI("https://api.gnavi.co.jp/RestSearchAPI/?"+query)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(uri)
    res = http.request(req)
    res_data = Hash.from_xml(res.body)
    restaurant = res_data["response"]["rest"]
    @image, @name, @tel, @url = restaurant["image_url"]["shop_image1"], restaurant["name"], restaurant["tel"], restaurant["url"]
    @pr = restaurant["pr"]["pr_long"]? restaurant["pr"]["pr_long"]: "PRはありません"
    @opentime = restaurant["opentime"]? restaurant["opentime"] : "営業時間は不明です"
    @address = restaurant["address"]? restaurant["address"].sub(/ /,"<br>") : "住所は不明です"
    @map_url = "https://maps.google.com/maps?q=#{restaurant["latitude"]},#{restaurant["longitude"]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> error"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<header class="col-12">
  <h1><%= link_to "restaurants", root_path, style: "color:white; text-decoration:none;" %></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:300,500&display=swap&subset=japanese" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <title>Restaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <div class="wrap">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_result.html.erb
<li class="media">
  <img class="mr-3 w-25" src="<%= restaurant["image_url"]["shop_image1"]%>" alt="画像なし"  onerror="this.src='/image.png'">
  <div class="media-body h-25 w-75">
    <h3 class="mt-0 mb-1 r_name"><%= link_to restaurant["name"], restaurants_data_path(id: restaurant["id"])%></h3>
    <h5 class="mt-0 mb-1">
      <% if restaurant["access"]["station"] %>
        最寄駅:<%= restaurant["access"]["station"] %>
      <% else %>
        最寄駅は不明です
      <% end %>
    </h5>
    <h5 class="mt-0 mb-1">
      <% if restaurant["access"]["walk"] %>
        <%= restaurant["access"]["walk"] %>分
      <% else %>
        距離は不明です
      <% end %>
    </h5>
    <h5 class="mt-0 mb-1">
      <% if restaurant["category"] %>
        カテゴリー:<%= restaurant["category"] %>
      <% else %>
        カテゴリーは不明です
      <% end %>
    </h5>
    <h5 class="mt-0 mb-1">
      <% if restaurant["budget"] %>
        平均予算:<%= restaurant["budget"] %>円
      <% else%>
        平均予算は不明です
      <% end%>
    </h5>
  </div>
</li>

app/views/restaurants/data.html.erb
<div class="row">
  <div class="col-2 ml-5 search_form h-50">
    <form name="search">
      <div class="form-group">
        <label for="radius">検索半径</label>
        <div class="input">
          <select name="radius" id="radius" class="form-control">
            <option value="1">300</option>
            <option value="2">500</option>
            <option value="3">1000</option>
            <option value="4">2000</option>
            <option value="5">3000</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label for="word">検索ワード</label>
        <div class="input">
          <input type="text" class="form-control" name="word" id="word" placeholder="（例）ラーメン">
        </div>
      </div>
    </form>
    <div class="right-button">
      <button type="submit" class="btn btn-primary" onclick="getPosition();">検索</button>
    </div>
  </div> 

  <div class="col-7 ml-5 restaurant row">
    <div class="r-image col-5" style="background-image: url(<%= @image? @image : '/image.png' %>);">
      <h4 class="w-100 pl-2"><%= @name %></h4>
      <a href ="<%= @url %>"></a>
    </div>
    <div class="col-6 basic_data pr-0">
      <h5 class="mb-1 mt-1">営業時間</h5>
      <h5><%= @opentime.html_safe %></h5>
      <h5 class="mt-2">電話番号 <%= @tel %></h5>
      <a href="<%= @map_url %>"><h5><%= @address.html_safe %></h5></a>
      <a href="//twitter.com/share" class="twitter-share-button" data-text="<%= @name %>" data-url="https://social-plugins.line.me/lineit/share?url=<%= @url %>" data-lang="ja">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      <div class="line-it-button" data-lang="ja" data-type="share-a" data-ver="3" data-url="<%= @url %>" data-color="default" data-size="small" data-count="false" style="display: none;"></div><script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
    </div>
    <div class="col-11 pt-2 pr-2 pl-2 pr">
      <p><%= @pr.html_safe %></p>
    </div>
  </div>
</div>

app/views/restaurants/search.html.erb
<div class="row">
  <div class="col-2 ml-5 search_form h-50">
    <form name="search">
      <div class="form-group">
        <label for="radius">検索半径</label>
        <div class="input">
          <select name="radius" id="radius" class="form-control">
            <option value="1">300</option>
            <option value="2">500</option>
            <option value="3">1000</option>
            <option value="4">2000</option>
            <option value="5">3000</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label for="word">検索ワード</label>
        <div class="input">
          <input type="text" class="form-control" name="word" id="word" placeholder = "(例)ラーメン,店名など" value="<%= params[:word] %>">
        </div>
      </div>
    </form>
    <div class="right-button">
      <button type="submit" class="btn btn-primary" onclick="getPosition();">検索</button>
    </div>
  </div>
  <div class="col-7 ml-3 pl-3">
    <% if @restaurants %>
      <ul class="list-unstyled w-100">
        <% @restaurants.each do |restaurant| %>
          <%= render "result", restaurant: restaurant %>
        <% end %>
      </ul>
      <h5 class="w-100"><%= paginate(@restaurants) %></h5>
    <% else %>
      <ul class="list-unstyled w-100">
        <%= render "result", restaurant: @restaurant %>
      </ul>
    <% end %>
  </div>
</div>

<script>
  document.getElementById('radius').options[<%= @range.to_i-1 %>].selected = true;
</script>

app/views/restaurants/top.html.erb
<div class="col-5 mx-auto info">
  <h5 class="mt-4">『restaurants』では</h5>
  <h5 class="mb-4 pl-3">現在地を取得して付近の飲食店を検索することが可能です。</h5>
</div>

<div class="row">
  <div class="col-6 mx-auto search_form mt-1">
  <h4>飲食店検索</h4>
    <form name="search">
      <div class="form-group row">
        <label for="radius" class="col-2 col-form-label">検索半径</label>
        <div class="col-10 input">
          <select name="radius" id="radius" class="form-control">
            <option value="1">300</option>
            <option value="2">500</option>
            <option value="3">1000</option>
            <option value="4">2000</option>
            <option value="5">3000</option>
          </select>
          <small class="text-muted">検索半径を選んでください。</small>
        </div>
      </div>
      <div class="form-group row">
        <label for="word" class="col-2 col-form-label">検索ワード</label>
        <div class="col-10 input">
          <input type="text" class="form-control" name="word" id="word" placeholder="(例)ラーメン,店名など">
          <small class="text-muted">※入力は自由です。コンマ(,)区切りで複数ワードが検索可能です(10個まで)。</small>
        </div>
      </div>
    </form>
    <div class="right-button">
      <button type="submit" class="btn btn-primary" onclick="getPosition();">検索する</button>
    </div>
  </div>
</div>